[".config/zsh/git-prompt.zsh"]
type = "file"
url = "https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh"
refreshPeriod = "168h"
filter.command = "sed"
filter.args = ["s/PS1=/RPS1=/"]

[".config/zsh/.zplug"]
type= "git-repo"
url = "https://github.com/zplug/zplug.git"
refreshPeriod = "168h"
clone.args = ["--depth", "1"]

[".git-prompt.sh"]
type = "file"
url = "https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh"
refreshPeriod = "168h"

[".local/share/nvim/site/pack/packer/start/packer.nvim"]
type = "git-repo"
url = "https://github.com/wbthomason/packer.nvim.git"
refreshPeriod = "168h"
clone.args = ["--depth", "1"]

[".tmux/plugins/tpm"]
type  = "git-repo"
url = "https://github.com/tmux-plugins/tpm.git"
refreshPeriod = "168h"
clone.args = ["--depth", "1"]

[".vim/autoload/plug.vim"]
type = "file"
url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
refreshPeriod = "168h"
