[".config/zsh/git-prompt.zsh"]
type = "file"
url = "https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh"
refreshPeriod = "168h"
filter.command = "sed"
filter.args = ["s/PS1=/RPS1=/"]

[".config/zsh/plugins/zsh-vi-mode"]
type= "git-repo"
url = "https://github.com/jeffreytse/zsh-vi-mode.git"
refreshPeriod = "168h"
clone.args = ["--depth", "1"]

[".config/zsh/plugins/zsh-autosuggestions"]
type= "git-repo"
url = "https://github.com/zsh-users/zsh-autosuggestions.git"
refreshPeriod = "168h"
clone.args = ["--depth", "1"]

[".config/zsh/plugins/zsh-syntax-highlighting"]
type= "git-repo"
url = "https://github.com/zsh-users/zsh-syntax-highlighting.git"
refreshPeriod = "168h"
clone.args = ["--depth", "1"]

[".git-prompt.sh"]
type = "file"
url = "https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh"
refreshPeriod = "168h"

[".tmux/plugins/tpm"]
type  = "git-repo"
url = "https://github.com/tmux-plugins/tpm.git"
refreshPeriod = "168h"
clone.args = ["--depth", "1"]

[".vim/autoload/plug.vim"]
type = "file"
url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
refreshPeriod = "168h"
