#!/usr/bin/env bash

URL='https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh'
TARGET="${HOME}/.dotfiles/config/zsh/git-prompt"
curl "$URL" | sed 's/PS1=/RPS1=/' > "$TARGET" \
	&& echo "__git_ps1 '' ''" >> "$TARGET"
