export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_DATA_HOME="${HOME}/.local/share"
export ZDOTDIR="${XDG_CONFIG_HOME}/zsh"
typeset -U PATH path
case $(uname -s) in
	'Darwin')
		export OS_CATEGORY='macos'
		export SHELL_SESSIONS_DISABLE='1'
		;;
	'Linux')
		eval $(cat /etc/os-release | grep 'ID_LIKE=')
		export OS_CATEGORY="$ID_LIKE"
		;;
esac
