export XDG_CONFIG_HOME="${HOME}/.config"
export ZDOTDIR="${XDG_CONFIG_HOME}/zsh"
typeset -U path
case $(uname -s) in
	'Darwin')
		export OS_CATEGORY='macos'
		export SHELL_SESSIONS_DISABLE='1'
		;;
	'Linux')
		eval $(cat /etc/os-release | grep 'ID_LIKE=')
		export OS_CATEGORY="$ID_LIKE"
		;;
esac
